theme: jekyll-theme-slate
title: Bioinformatics Learn Infinite
description: Mastering and polishing technical wherewithal in bioinformatics.
permalink: pretty
defaults:
  - scope:
      path: ""
    values:
      layout: default
show_downloads: false
feedback:
  max_words: 120
  endpoint: "https://formsubmit.co/raymondotoo115@gmail.com"
